/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeachingRouteRouteImport } from './routes/teaching/route'
import { Route as MeRouteRouteImport } from './routes/me/route'
import { Route as ImprovisingRouteRouteImport } from './routes/improvising/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeachingIndexRouteImport } from './routes/teaching/index'
import { Route as ImprovisingIndexRouteImport } from './routes/improvising/index'
import { Route as TeachingWorkshopsTheIdiotRouteImport } from './routes/teaching/workshops/the-idiot'
import { Route as TeachingWorkshopsStartingOverAndOverRouteImport } from './routes/teaching/workshops/starting-over-and-over'
import { Route as TeachingWorkshopsSneakingUpOnYourselfRouteImport } from './routes/teaching/workshops/sneaking-up-on-yourself'
import { Route as TeachingWorkshopsScenesThatSuckRouteImport } from './routes/teaching/workshops/scenes-that-suck'
import { Route as TeachingWorkshopsReadingTheSceneRouteImport } from './routes/teaching/workshops/reading-the-scene'
import { Route as TeachingWorkshopsNothingHappenedTodayRouteImport } from './routes/teaching/workshops/nothing-happened-today'
import { Route as TeachingWorkshopsEnPointeRouteImport } from './routes/teaching/workshops/en-pointe'
import { Route as TeachingWorkshopsBigMeMcSkillsRouteImport } from './routes/teaching/workshops/big-me-mc-skills'
import { Route as ImprovisingShowsYourExtraordinaryLifeRouteImport } from './routes/improvising/shows/your-extraordinary-life'
import { Route as ImprovisingShowsTheHistoryBoyRouteImport } from './routes/improvising/shows/the-history-boy'
import { Route as ImprovisingShowsSpontadeityRouteImport } from './routes/improvising/shows/spontadeity'
import { Route as ImprovisingShowsJerichoFallsRouteImport } from './routes/improvising/shows/jericho-falls'
import { Route as ImprovisingShowsItsDangerousToGoAloneRouteImport } from './routes/improvising/shows/its-dangerous-to-go-alone'
import { Route as ImprovisingShowsDontSeeThisShowAloneRouteImport } from './routes/improvising/shows/dont-see-this-show-alone'
import { Route as ImprovisingShowsCupidsGuideToModernRomanceRouteImport } from './routes/improvising/shows/cupids-guide-to-modern-romance'
import { Route as ImprovisingShowsAwkwardThreesomeRouteImport } from './routes/improvising/shows/awkward-threesome'

const TeachingRouteRoute = TeachingRouteRouteImport.update({
  id: '/teaching',
  path: '/teaching',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRouteRoute = MeRouteRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprovisingRouteRoute = ImprovisingRouteRouteImport.update({
  id: '/improvising',
  path: '/improvising',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachingIndexRoute = TeachingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeachingRouteRoute,
} as any)
const ImprovisingIndexRoute = ImprovisingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ImprovisingRouteRoute,
} as any)
const TeachingWorkshopsTheIdiotRoute =
  TeachingWorkshopsTheIdiotRouteImport.update({
    id: '/workshops/the-idiot',
    path: '/workshops/the-idiot',
    getParentRoute: () => TeachingRouteRoute,
  } as any)
const TeachingWorkshopsStartingOverAndOverRoute =
  TeachingWorkshopsStartingOverAndOverRouteImport.update({
    id: '/workshops/starting-over-and-over',
    path: '/workshops/starting-over-and-over',
    getParentRoute: () => TeachingRouteRoute,
  } as any)
const TeachingWorkshopsSneakingUpOnYourselfRoute =
  TeachingWorkshopsSneakingUpOnYourselfRouteImport.update({
    id: '/workshops/sneaking-up-on-yourself',
    path: '/workshops/sneaking-up-on-yourself',
    getParentRoute: () => TeachingRouteRoute,
  } as any)
const TeachingWorkshopsScenesThatSuckRoute =
  TeachingWorkshopsScenesThatSuckRouteImport.update({
    id: '/workshops/scenes-that-suck',
    path: '/workshops/scenes-that-suck',
    getParentRoute: () => TeachingRouteRoute,
  } as any)
const TeachingWorkshopsReadingTheSceneRoute =
  TeachingWorkshopsReadingTheSceneRouteImport.update({
    id: '/workshops/reading-the-scene',
    path: '/workshops/reading-the-scene',
    getParentRoute: () => TeachingRouteRoute,
  } as any)
const TeachingWorkshopsNothingHappenedTodayRoute =
  TeachingWorkshopsNothingHappenedTodayRouteImport.update({
    id: '/workshops/nothing-happened-today',
    path: '/workshops/nothing-happened-today',
    getParentRoute: () => TeachingRouteRoute,
  } as any)
const TeachingWorkshopsEnPointeRoute =
  TeachingWorkshopsEnPointeRouteImport.update({
    id: '/workshops/en-pointe',
    path: '/workshops/en-pointe',
    getParentRoute: () => TeachingRouteRoute,
  } as any)
const TeachingWorkshopsBigMeMcSkillsRoute =
  TeachingWorkshopsBigMeMcSkillsRouteImport.update({
    id: '/workshops/big-me-mc-skills',
    path: '/workshops/big-me-mc-skills',
    getParentRoute: () => TeachingRouteRoute,
  } as any)
const ImprovisingShowsYourExtraordinaryLifeRoute =
  ImprovisingShowsYourExtraordinaryLifeRouteImport.update({
    id: '/shows/your-extraordinary-life',
    path: '/shows/your-extraordinary-life',
    getParentRoute: () => ImprovisingRouteRoute,
  } as any)
const ImprovisingShowsTheHistoryBoyRoute =
  ImprovisingShowsTheHistoryBoyRouteImport.update({
    id: '/shows/the-history-boy',
    path: '/shows/the-history-boy',
    getParentRoute: () => ImprovisingRouteRoute,
  } as any)
const ImprovisingShowsSpontadeityRoute =
  ImprovisingShowsSpontadeityRouteImport.update({
    id: '/shows/spontadeity',
    path: '/shows/spontadeity',
    getParentRoute: () => ImprovisingRouteRoute,
  } as any)
const ImprovisingShowsJerichoFallsRoute =
  ImprovisingShowsJerichoFallsRouteImport.update({
    id: '/shows/jericho-falls',
    path: '/shows/jericho-falls',
    getParentRoute: () => ImprovisingRouteRoute,
  } as any)
const ImprovisingShowsItsDangerousToGoAloneRoute =
  ImprovisingShowsItsDangerousToGoAloneRouteImport.update({
    id: '/shows/its-dangerous-to-go-alone',
    path: '/shows/its-dangerous-to-go-alone',
    getParentRoute: () => ImprovisingRouteRoute,
  } as any)
const ImprovisingShowsDontSeeThisShowAloneRoute =
  ImprovisingShowsDontSeeThisShowAloneRouteImport.update({
    id: '/shows/dont-see-this-show-alone',
    path: '/shows/dont-see-this-show-alone',
    getParentRoute: () => ImprovisingRouteRoute,
  } as any)
const ImprovisingShowsCupidsGuideToModernRomanceRoute =
  ImprovisingShowsCupidsGuideToModernRomanceRouteImport.update({
    id: '/shows/cupids-guide-to-modern-romance',
    path: '/shows/cupids-guide-to-modern-romance',
    getParentRoute: () => ImprovisingRouteRoute,
  } as any)
const ImprovisingShowsAwkwardThreesomeRoute =
  ImprovisingShowsAwkwardThreesomeRouteImport.update({
    id: '/shows/awkward-threesome',
    path: '/shows/awkward-threesome',
    getParentRoute: () => ImprovisingRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/improvising': typeof ImprovisingRouteRouteWithChildren
  '/me': typeof MeRouteRoute
  '/teaching': typeof TeachingRouteRouteWithChildren
  '/improvising/': typeof ImprovisingIndexRoute
  '/teaching/': typeof TeachingIndexRoute
  '/improvising/shows/awkward-threesome': typeof ImprovisingShowsAwkwardThreesomeRoute
  '/improvising/shows/cupids-guide-to-modern-romance': typeof ImprovisingShowsCupidsGuideToModernRomanceRoute
  '/improvising/shows/dont-see-this-show-alone': typeof ImprovisingShowsDontSeeThisShowAloneRoute
  '/improvising/shows/its-dangerous-to-go-alone': typeof ImprovisingShowsItsDangerousToGoAloneRoute
  '/improvising/shows/jericho-falls': typeof ImprovisingShowsJerichoFallsRoute
  '/improvising/shows/spontadeity': typeof ImprovisingShowsSpontadeityRoute
  '/improvising/shows/the-history-boy': typeof ImprovisingShowsTheHistoryBoyRoute
  '/improvising/shows/your-extraordinary-life': typeof ImprovisingShowsYourExtraordinaryLifeRoute
  '/teaching/workshops/big-me-mc-skills': typeof TeachingWorkshopsBigMeMcSkillsRoute
  '/teaching/workshops/en-pointe': typeof TeachingWorkshopsEnPointeRoute
  '/teaching/workshops/nothing-happened-today': typeof TeachingWorkshopsNothingHappenedTodayRoute
  '/teaching/workshops/reading-the-scene': typeof TeachingWorkshopsReadingTheSceneRoute
  '/teaching/workshops/scenes-that-suck': typeof TeachingWorkshopsScenesThatSuckRoute
  '/teaching/workshops/sneaking-up-on-yourself': typeof TeachingWorkshopsSneakingUpOnYourselfRoute
  '/teaching/workshops/starting-over-and-over': typeof TeachingWorkshopsStartingOverAndOverRoute
  '/teaching/workshops/the-idiot': typeof TeachingWorkshopsTheIdiotRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/me': typeof MeRouteRoute
  '/improvising': typeof ImprovisingIndexRoute
  '/teaching': typeof TeachingIndexRoute
  '/improvising/shows/awkward-threesome': typeof ImprovisingShowsAwkwardThreesomeRoute
  '/improvising/shows/cupids-guide-to-modern-romance': typeof ImprovisingShowsCupidsGuideToModernRomanceRoute
  '/improvising/shows/dont-see-this-show-alone': typeof ImprovisingShowsDontSeeThisShowAloneRoute
  '/improvising/shows/its-dangerous-to-go-alone': typeof ImprovisingShowsItsDangerousToGoAloneRoute
  '/improvising/shows/jericho-falls': typeof ImprovisingShowsJerichoFallsRoute
  '/improvising/shows/spontadeity': typeof ImprovisingShowsSpontadeityRoute
  '/improvising/shows/the-history-boy': typeof ImprovisingShowsTheHistoryBoyRoute
  '/improvising/shows/your-extraordinary-life': typeof ImprovisingShowsYourExtraordinaryLifeRoute
  '/teaching/workshops/big-me-mc-skills': typeof TeachingWorkshopsBigMeMcSkillsRoute
  '/teaching/workshops/en-pointe': typeof TeachingWorkshopsEnPointeRoute
  '/teaching/workshops/nothing-happened-today': typeof TeachingWorkshopsNothingHappenedTodayRoute
  '/teaching/workshops/reading-the-scene': typeof TeachingWorkshopsReadingTheSceneRoute
  '/teaching/workshops/scenes-that-suck': typeof TeachingWorkshopsScenesThatSuckRoute
  '/teaching/workshops/sneaking-up-on-yourself': typeof TeachingWorkshopsSneakingUpOnYourselfRoute
  '/teaching/workshops/starting-over-and-over': typeof TeachingWorkshopsStartingOverAndOverRoute
  '/teaching/workshops/the-idiot': typeof TeachingWorkshopsTheIdiotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/improvising': typeof ImprovisingRouteRouteWithChildren
  '/me': typeof MeRouteRoute
  '/teaching': typeof TeachingRouteRouteWithChildren
  '/improvising/': typeof ImprovisingIndexRoute
  '/teaching/': typeof TeachingIndexRoute
  '/improvising/shows/awkward-threesome': typeof ImprovisingShowsAwkwardThreesomeRoute
  '/improvising/shows/cupids-guide-to-modern-romance': typeof ImprovisingShowsCupidsGuideToModernRomanceRoute
  '/improvising/shows/dont-see-this-show-alone': typeof ImprovisingShowsDontSeeThisShowAloneRoute
  '/improvising/shows/its-dangerous-to-go-alone': typeof ImprovisingShowsItsDangerousToGoAloneRoute
  '/improvising/shows/jericho-falls': typeof ImprovisingShowsJerichoFallsRoute
  '/improvising/shows/spontadeity': typeof ImprovisingShowsSpontadeityRoute
  '/improvising/shows/the-history-boy': typeof ImprovisingShowsTheHistoryBoyRoute
  '/improvising/shows/your-extraordinary-life': typeof ImprovisingShowsYourExtraordinaryLifeRoute
  '/teaching/workshops/big-me-mc-skills': typeof TeachingWorkshopsBigMeMcSkillsRoute
  '/teaching/workshops/en-pointe': typeof TeachingWorkshopsEnPointeRoute
  '/teaching/workshops/nothing-happened-today': typeof TeachingWorkshopsNothingHappenedTodayRoute
  '/teaching/workshops/reading-the-scene': typeof TeachingWorkshopsReadingTheSceneRoute
  '/teaching/workshops/scenes-that-suck': typeof TeachingWorkshopsScenesThatSuckRoute
  '/teaching/workshops/sneaking-up-on-yourself': typeof TeachingWorkshopsSneakingUpOnYourselfRoute
  '/teaching/workshops/starting-over-and-over': typeof TeachingWorkshopsStartingOverAndOverRoute
  '/teaching/workshops/the-idiot': typeof TeachingWorkshopsTheIdiotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/improvising'
    | '/me'
    | '/teaching'
    | '/improvising/'
    | '/teaching/'
    | '/improvising/shows/awkward-threesome'
    | '/improvising/shows/cupids-guide-to-modern-romance'
    | '/improvising/shows/dont-see-this-show-alone'
    | '/improvising/shows/its-dangerous-to-go-alone'
    | '/improvising/shows/jericho-falls'
    | '/improvising/shows/spontadeity'
    | '/improvising/shows/the-history-boy'
    | '/improvising/shows/your-extraordinary-life'
    | '/teaching/workshops/big-me-mc-skills'
    | '/teaching/workshops/en-pointe'
    | '/teaching/workshops/nothing-happened-today'
    | '/teaching/workshops/reading-the-scene'
    | '/teaching/workshops/scenes-that-suck'
    | '/teaching/workshops/sneaking-up-on-yourself'
    | '/teaching/workshops/starting-over-and-over'
    | '/teaching/workshops/the-idiot'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/me'
    | '/improvising'
    | '/teaching'
    | '/improvising/shows/awkward-threesome'
    | '/improvising/shows/cupids-guide-to-modern-romance'
    | '/improvising/shows/dont-see-this-show-alone'
    | '/improvising/shows/its-dangerous-to-go-alone'
    | '/improvising/shows/jericho-falls'
    | '/improvising/shows/spontadeity'
    | '/improvising/shows/the-history-boy'
    | '/improvising/shows/your-extraordinary-life'
    | '/teaching/workshops/big-me-mc-skills'
    | '/teaching/workshops/en-pointe'
    | '/teaching/workshops/nothing-happened-today'
    | '/teaching/workshops/reading-the-scene'
    | '/teaching/workshops/scenes-that-suck'
    | '/teaching/workshops/sneaking-up-on-yourself'
    | '/teaching/workshops/starting-over-and-over'
    | '/teaching/workshops/the-idiot'
  id:
    | '__root__'
    | '/'
    | '/improvising'
    | '/me'
    | '/teaching'
    | '/improvising/'
    | '/teaching/'
    | '/improvising/shows/awkward-threesome'
    | '/improvising/shows/cupids-guide-to-modern-romance'
    | '/improvising/shows/dont-see-this-show-alone'
    | '/improvising/shows/its-dangerous-to-go-alone'
    | '/improvising/shows/jericho-falls'
    | '/improvising/shows/spontadeity'
    | '/improvising/shows/the-history-boy'
    | '/improvising/shows/your-extraordinary-life'
    | '/teaching/workshops/big-me-mc-skills'
    | '/teaching/workshops/en-pointe'
    | '/teaching/workshops/nothing-happened-today'
    | '/teaching/workshops/reading-the-scene'
    | '/teaching/workshops/scenes-that-suck'
    | '/teaching/workshops/sneaking-up-on-yourself'
    | '/teaching/workshops/starting-over-and-over'
    | '/teaching/workshops/the-idiot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImprovisingRouteRoute: typeof ImprovisingRouteRouteWithChildren
  MeRouteRoute: typeof MeRouteRoute
  TeachingRouteRoute: typeof TeachingRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teaching': {
      id: '/teaching'
      path: '/teaching'
      fullPath: '/teaching'
      preLoaderRoute: typeof TeachingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/improvising': {
      id: '/improvising'
      path: '/improvising'
      fullPath: '/improvising'
      preLoaderRoute: typeof ImprovisingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teaching/': {
      id: '/teaching/'
      path: '/'
      fullPath: '/teaching/'
      preLoaderRoute: typeof TeachingIndexRouteImport
      parentRoute: typeof TeachingRouteRoute
    }
    '/improvising/': {
      id: '/improvising/'
      path: '/'
      fullPath: '/improvising/'
      preLoaderRoute: typeof ImprovisingIndexRouteImport
      parentRoute: typeof ImprovisingRouteRoute
    }
    '/teaching/workshops/the-idiot': {
      id: '/teaching/workshops/the-idiot'
      path: '/workshops/the-idiot'
      fullPath: '/teaching/workshops/the-idiot'
      preLoaderRoute: typeof TeachingWorkshopsTheIdiotRouteImport
      parentRoute: typeof TeachingRouteRoute
    }
    '/teaching/workshops/starting-over-and-over': {
      id: '/teaching/workshops/starting-over-and-over'
      path: '/workshops/starting-over-and-over'
      fullPath: '/teaching/workshops/starting-over-and-over'
      preLoaderRoute: typeof TeachingWorkshopsStartingOverAndOverRouteImport
      parentRoute: typeof TeachingRouteRoute
    }
    '/teaching/workshops/sneaking-up-on-yourself': {
      id: '/teaching/workshops/sneaking-up-on-yourself'
      path: '/workshops/sneaking-up-on-yourself'
      fullPath: '/teaching/workshops/sneaking-up-on-yourself'
      preLoaderRoute: typeof TeachingWorkshopsSneakingUpOnYourselfRouteImport
      parentRoute: typeof TeachingRouteRoute
    }
    '/teaching/workshops/scenes-that-suck': {
      id: '/teaching/workshops/scenes-that-suck'
      path: '/workshops/scenes-that-suck'
      fullPath: '/teaching/workshops/scenes-that-suck'
      preLoaderRoute: typeof TeachingWorkshopsScenesThatSuckRouteImport
      parentRoute: typeof TeachingRouteRoute
    }
    '/teaching/workshops/reading-the-scene': {
      id: '/teaching/workshops/reading-the-scene'
      path: '/workshops/reading-the-scene'
      fullPath: '/teaching/workshops/reading-the-scene'
      preLoaderRoute: typeof TeachingWorkshopsReadingTheSceneRouteImport
      parentRoute: typeof TeachingRouteRoute
    }
    '/teaching/workshops/nothing-happened-today': {
      id: '/teaching/workshops/nothing-happened-today'
      path: '/workshops/nothing-happened-today'
      fullPath: '/teaching/workshops/nothing-happened-today'
      preLoaderRoute: typeof TeachingWorkshopsNothingHappenedTodayRouteImport
      parentRoute: typeof TeachingRouteRoute
    }
    '/teaching/workshops/en-pointe': {
      id: '/teaching/workshops/en-pointe'
      path: '/workshops/en-pointe'
      fullPath: '/teaching/workshops/en-pointe'
      preLoaderRoute: typeof TeachingWorkshopsEnPointeRouteImport
      parentRoute: typeof TeachingRouteRoute
    }
    '/teaching/workshops/big-me-mc-skills': {
      id: '/teaching/workshops/big-me-mc-skills'
      path: '/workshops/big-me-mc-skills'
      fullPath: '/teaching/workshops/big-me-mc-skills'
      preLoaderRoute: typeof TeachingWorkshopsBigMeMcSkillsRouteImport
      parentRoute: typeof TeachingRouteRoute
    }
    '/improvising/shows/your-extraordinary-life': {
      id: '/improvising/shows/your-extraordinary-life'
      path: '/shows/your-extraordinary-life'
      fullPath: '/improvising/shows/your-extraordinary-life'
      preLoaderRoute: typeof ImprovisingShowsYourExtraordinaryLifeRouteImport
      parentRoute: typeof ImprovisingRouteRoute
    }
    '/improvising/shows/the-history-boy': {
      id: '/improvising/shows/the-history-boy'
      path: '/shows/the-history-boy'
      fullPath: '/improvising/shows/the-history-boy'
      preLoaderRoute: typeof ImprovisingShowsTheHistoryBoyRouteImport
      parentRoute: typeof ImprovisingRouteRoute
    }
    '/improvising/shows/spontadeity': {
      id: '/improvising/shows/spontadeity'
      path: '/shows/spontadeity'
      fullPath: '/improvising/shows/spontadeity'
      preLoaderRoute: typeof ImprovisingShowsSpontadeityRouteImport
      parentRoute: typeof ImprovisingRouteRoute
    }
    '/improvising/shows/jericho-falls': {
      id: '/improvising/shows/jericho-falls'
      path: '/shows/jericho-falls'
      fullPath: '/improvising/shows/jericho-falls'
      preLoaderRoute: typeof ImprovisingShowsJerichoFallsRouteImport
      parentRoute: typeof ImprovisingRouteRoute
    }
    '/improvising/shows/its-dangerous-to-go-alone': {
      id: '/improvising/shows/its-dangerous-to-go-alone'
      path: '/shows/its-dangerous-to-go-alone'
      fullPath: '/improvising/shows/its-dangerous-to-go-alone'
      preLoaderRoute: typeof ImprovisingShowsItsDangerousToGoAloneRouteImport
      parentRoute: typeof ImprovisingRouteRoute
    }
    '/improvising/shows/dont-see-this-show-alone': {
      id: '/improvising/shows/dont-see-this-show-alone'
      path: '/shows/dont-see-this-show-alone'
      fullPath: '/improvising/shows/dont-see-this-show-alone'
      preLoaderRoute: typeof ImprovisingShowsDontSeeThisShowAloneRouteImport
      parentRoute: typeof ImprovisingRouteRoute
    }
    '/improvising/shows/cupids-guide-to-modern-romance': {
      id: '/improvising/shows/cupids-guide-to-modern-romance'
      path: '/shows/cupids-guide-to-modern-romance'
      fullPath: '/improvising/shows/cupids-guide-to-modern-romance'
      preLoaderRoute: typeof ImprovisingShowsCupidsGuideToModernRomanceRouteImport
      parentRoute: typeof ImprovisingRouteRoute
    }
    '/improvising/shows/awkward-threesome': {
      id: '/improvising/shows/awkward-threesome'
      path: '/shows/awkward-threesome'
      fullPath: '/improvising/shows/awkward-threesome'
      preLoaderRoute: typeof ImprovisingShowsAwkwardThreesomeRouteImport
      parentRoute: typeof ImprovisingRouteRoute
    }
  }
}

interface ImprovisingRouteRouteChildren {
  ImprovisingIndexRoute: typeof ImprovisingIndexRoute
  ImprovisingShowsAwkwardThreesomeRoute: typeof ImprovisingShowsAwkwardThreesomeRoute
  ImprovisingShowsCupidsGuideToModernRomanceRoute: typeof ImprovisingShowsCupidsGuideToModernRomanceRoute
  ImprovisingShowsDontSeeThisShowAloneRoute: typeof ImprovisingShowsDontSeeThisShowAloneRoute
  ImprovisingShowsItsDangerousToGoAloneRoute: typeof ImprovisingShowsItsDangerousToGoAloneRoute
  ImprovisingShowsJerichoFallsRoute: typeof ImprovisingShowsJerichoFallsRoute
  ImprovisingShowsSpontadeityRoute: typeof ImprovisingShowsSpontadeityRoute
  ImprovisingShowsTheHistoryBoyRoute: typeof ImprovisingShowsTheHistoryBoyRoute
  ImprovisingShowsYourExtraordinaryLifeRoute: typeof ImprovisingShowsYourExtraordinaryLifeRoute
}

const ImprovisingRouteRouteChildren: ImprovisingRouteRouteChildren = {
  ImprovisingIndexRoute: ImprovisingIndexRoute,
  ImprovisingShowsAwkwardThreesomeRoute: ImprovisingShowsAwkwardThreesomeRoute,
  ImprovisingShowsCupidsGuideToModernRomanceRoute:
    ImprovisingShowsCupidsGuideToModernRomanceRoute,
  ImprovisingShowsDontSeeThisShowAloneRoute:
    ImprovisingShowsDontSeeThisShowAloneRoute,
  ImprovisingShowsItsDangerousToGoAloneRoute:
    ImprovisingShowsItsDangerousToGoAloneRoute,
  ImprovisingShowsJerichoFallsRoute: ImprovisingShowsJerichoFallsRoute,
  ImprovisingShowsSpontadeityRoute: ImprovisingShowsSpontadeityRoute,
  ImprovisingShowsTheHistoryBoyRoute: ImprovisingShowsTheHistoryBoyRoute,
  ImprovisingShowsYourExtraordinaryLifeRoute:
    ImprovisingShowsYourExtraordinaryLifeRoute,
}

const ImprovisingRouteRouteWithChildren =
  ImprovisingRouteRoute._addFileChildren(ImprovisingRouteRouteChildren)

interface TeachingRouteRouteChildren {
  TeachingIndexRoute: typeof TeachingIndexRoute
  TeachingWorkshopsBigMeMcSkillsRoute: typeof TeachingWorkshopsBigMeMcSkillsRoute
  TeachingWorkshopsEnPointeRoute: typeof TeachingWorkshopsEnPointeRoute
  TeachingWorkshopsNothingHappenedTodayRoute: typeof TeachingWorkshopsNothingHappenedTodayRoute
  TeachingWorkshopsReadingTheSceneRoute: typeof TeachingWorkshopsReadingTheSceneRoute
  TeachingWorkshopsScenesThatSuckRoute: typeof TeachingWorkshopsScenesThatSuckRoute
  TeachingWorkshopsSneakingUpOnYourselfRoute: typeof TeachingWorkshopsSneakingUpOnYourselfRoute
  TeachingWorkshopsStartingOverAndOverRoute: typeof TeachingWorkshopsStartingOverAndOverRoute
  TeachingWorkshopsTheIdiotRoute: typeof TeachingWorkshopsTheIdiotRoute
}

const TeachingRouteRouteChildren: TeachingRouteRouteChildren = {
  TeachingIndexRoute: TeachingIndexRoute,
  TeachingWorkshopsBigMeMcSkillsRoute: TeachingWorkshopsBigMeMcSkillsRoute,
  TeachingWorkshopsEnPointeRoute: TeachingWorkshopsEnPointeRoute,
  TeachingWorkshopsNothingHappenedTodayRoute:
    TeachingWorkshopsNothingHappenedTodayRoute,
  TeachingWorkshopsReadingTheSceneRoute: TeachingWorkshopsReadingTheSceneRoute,
  TeachingWorkshopsScenesThatSuckRoute: TeachingWorkshopsScenesThatSuckRoute,
  TeachingWorkshopsSneakingUpOnYourselfRoute:
    TeachingWorkshopsSneakingUpOnYourselfRoute,
  TeachingWorkshopsStartingOverAndOverRoute:
    TeachingWorkshopsStartingOverAndOverRoute,
  TeachingWorkshopsTheIdiotRoute: TeachingWorkshopsTheIdiotRoute,
}

const TeachingRouteRouteWithChildren = TeachingRouteRoute._addFileChildren(
  TeachingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImprovisingRouteRoute: ImprovisingRouteRouteWithChildren,
  MeRouteRoute: MeRouteRoute,
  TeachingRouteRoute: TeachingRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
