/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeachingRouteRouteImport } from './routes/teaching/route'
import { Route as MeRouteRouteImport } from './routes/me/route'
import { Route as ImprovisingRouteRouteImport } from './routes/improvising/route'
import { Route as IndexRouteImport } from './routes/index'

const TeachingRouteRoute = TeachingRouteRouteImport.update({
  id: '/teaching',
  path: '/teaching',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRouteRoute = MeRouteRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprovisingRouteRoute = ImprovisingRouteRouteImport.update({
  id: '/improvising',
  path: '/improvising',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/improvising': typeof ImprovisingRouteRoute
  '/me': typeof MeRouteRoute
  '/teaching': typeof TeachingRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/improvising': typeof ImprovisingRouteRoute
  '/me': typeof MeRouteRoute
  '/teaching': typeof TeachingRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/improvising': typeof ImprovisingRouteRoute
  '/me': typeof MeRouteRoute
  '/teaching': typeof TeachingRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/improvising' | '/me' | '/teaching'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/improvising' | '/me' | '/teaching'
  id: '__root__' | '/' | '/improvising' | '/me' | '/teaching'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImprovisingRouteRoute: typeof ImprovisingRouteRoute
  MeRouteRoute: typeof MeRouteRoute
  TeachingRouteRoute: typeof TeachingRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teaching': {
      id: '/teaching'
      path: '/teaching'
      fullPath: '/teaching'
      preLoaderRoute: typeof TeachingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/improvising': {
      id: '/improvising'
      path: '/improvising'
      fullPath: '/improvising'
      preLoaderRoute: typeof ImprovisingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImprovisingRouteRoute: ImprovisingRouteRoute,
  MeRouteRoute: MeRouteRoute,
  TeachingRouteRoute: TeachingRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
