/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeachingRouteRouteImport } from './routes/teaching/route'
import { Route as MeRouteRouteImport } from './routes/me/route'
import { Route as ImprovisingRouteRouteImport } from './routes/improvising/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeachingIndexRouteImport } from './routes/teaching/index'
import { Route as TeachingWorkshopsTheIdiotRouteImport } from './routes/teaching/workshops/the-idiot'
import { Route as TeachingWorkshopsStartingOverAndOverRouteImport } from './routes/teaching/workshops/starting-over-and-over'
import { Route as TeachingWorkshopsSneakingUpOnYourselfRouteImport } from './routes/teaching/workshops/sneaking-up-on-yourself'
import { Route as TeachingWorkshopsScenesThatSuckRouteImport } from './routes/teaching/workshops/scenes-that-suck'
import { Route as TeachingWorkshopsReadingTheSceneRouteImport } from './routes/teaching/workshops/reading-the-scene'
import { Route as TeachingWorkshopsNothingHappenedTodayRouteImport } from './routes/teaching/workshops/nothing-happened-today'
import { Route as TeachingWorkshopsEnPointeRouteImport } from './routes/teaching/workshops/en-pointe'
import { Route as TeachingWorkshopsBigMeMcSkillsRouteImport } from './routes/teaching/workshops/big-me-mc-skills'

const TeachingRouteRoute = TeachingRouteRouteImport.update({
  id: '/teaching',
  path: '/teaching',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRouteRoute = MeRouteRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprovisingRouteRoute = ImprovisingRouteRouteImport.update({
  id: '/improvising',
  path: '/improvising',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachingIndexRoute = TeachingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeachingRouteRoute,
} as any)
const TeachingWorkshopsTheIdiotRoute =
  TeachingWorkshopsTheIdiotRouteImport.update({
    id: '/workshops/the-idiot',
    path: '/workshops/the-idiot',
    getParentRoute: () => TeachingRouteRoute,
  } as any)
const TeachingWorkshopsStartingOverAndOverRoute =
  TeachingWorkshopsStartingOverAndOverRouteImport.update({
    id: '/workshops/starting-over-and-over',
    path: '/workshops/starting-over-and-over',
    getParentRoute: () => TeachingRouteRoute,
  } as any)
const TeachingWorkshopsSneakingUpOnYourselfRoute =
  TeachingWorkshopsSneakingUpOnYourselfRouteImport.update({
    id: '/workshops/sneaking-up-on-yourself',
    path: '/workshops/sneaking-up-on-yourself',
    getParentRoute: () => TeachingRouteRoute,
  } as any)
const TeachingWorkshopsScenesThatSuckRoute =
  TeachingWorkshopsScenesThatSuckRouteImport.update({
    id: '/workshops/scenes-that-suck',
    path: '/workshops/scenes-that-suck',
    getParentRoute: () => TeachingRouteRoute,
  } as any)
const TeachingWorkshopsReadingTheSceneRoute =
  TeachingWorkshopsReadingTheSceneRouteImport.update({
    id: '/workshops/reading-the-scene',
    path: '/workshops/reading-the-scene',
    getParentRoute: () => TeachingRouteRoute,
  } as any)
const TeachingWorkshopsNothingHappenedTodayRoute =
  TeachingWorkshopsNothingHappenedTodayRouteImport.update({
    id: '/workshops/nothing-happened-today',
    path: '/workshops/nothing-happened-today',
    getParentRoute: () => TeachingRouteRoute,
  } as any)
const TeachingWorkshopsEnPointeRoute =
  TeachingWorkshopsEnPointeRouteImport.update({
    id: '/workshops/en-pointe',
    path: '/workshops/en-pointe',
    getParentRoute: () => TeachingRouteRoute,
  } as any)
const TeachingWorkshopsBigMeMcSkillsRoute =
  TeachingWorkshopsBigMeMcSkillsRouteImport.update({
    id: '/workshops/big-me-mc-skills',
    path: '/workshops/big-me-mc-skills',
    getParentRoute: () => TeachingRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/improvising': typeof ImprovisingRouteRoute
  '/me': typeof MeRouteRoute
  '/teaching': typeof TeachingRouteRouteWithChildren
  '/teaching/': typeof TeachingIndexRoute
  '/teaching/workshops/big-me-mc-skills': typeof TeachingWorkshopsBigMeMcSkillsRoute
  '/teaching/workshops/en-pointe': typeof TeachingWorkshopsEnPointeRoute
  '/teaching/workshops/nothing-happened-today': typeof TeachingWorkshopsNothingHappenedTodayRoute
  '/teaching/workshops/reading-the-scene': typeof TeachingWorkshopsReadingTheSceneRoute
  '/teaching/workshops/scenes-that-suck': typeof TeachingWorkshopsScenesThatSuckRoute
  '/teaching/workshops/sneaking-up-on-yourself': typeof TeachingWorkshopsSneakingUpOnYourselfRoute
  '/teaching/workshops/starting-over-and-over': typeof TeachingWorkshopsStartingOverAndOverRoute
  '/teaching/workshops/the-idiot': typeof TeachingWorkshopsTheIdiotRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/improvising': typeof ImprovisingRouteRoute
  '/me': typeof MeRouteRoute
  '/teaching': typeof TeachingIndexRoute
  '/teaching/workshops/big-me-mc-skills': typeof TeachingWorkshopsBigMeMcSkillsRoute
  '/teaching/workshops/en-pointe': typeof TeachingWorkshopsEnPointeRoute
  '/teaching/workshops/nothing-happened-today': typeof TeachingWorkshopsNothingHappenedTodayRoute
  '/teaching/workshops/reading-the-scene': typeof TeachingWorkshopsReadingTheSceneRoute
  '/teaching/workshops/scenes-that-suck': typeof TeachingWorkshopsScenesThatSuckRoute
  '/teaching/workshops/sneaking-up-on-yourself': typeof TeachingWorkshopsSneakingUpOnYourselfRoute
  '/teaching/workshops/starting-over-and-over': typeof TeachingWorkshopsStartingOverAndOverRoute
  '/teaching/workshops/the-idiot': typeof TeachingWorkshopsTheIdiotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/improvising': typeof ImprovisingRouteRoute
  '/me': typeof MeRouteRoute
  '/teaching': typeof TeachingRouteRouteWithChildren
  '/teaching/': typeof TeachingIndexRoute
  '/teaching/workshops/big-me-mc-skills': typeof TeachingWorkshopsBigMeMcSkillsRoute
  '/teaching/workshops/en-pointe': typeof TeachingWorkshopsEnPointeRoute
  '/teaching/workshops/nothing-happened-today': typeof TeachingWorkshopsNothingHappenedTodayRoute
  '/teaching/workshops/reading-the-scene': typeof TeachingWorkshopsReadingTheSceneRoute
  '/teaching/workshops/scenes-that-suck': typeof TeachingWorkshopsScenesThatSuckRoute
  '/teaching/workshops/sneaking-up-on-yourself': typeof TeachingWorkshopsSneakingUpOnYourselfRoute
  '/teaching/workshops/starting-over-and-over': typeof TeachingWorkshopsStartingOverAndOverRoute
  '/teaching/workshops/the-idiot': typeof TeachingWorkshopsTheIdiotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/improvising'
    | '/me'
    | '/teaching'
    | '/teaching/'
    | '/teaching/workshops/big-me-mc-skills'
    | '/teaching/workshops/en-pointe'
    | '/teaching/workshops/nothing-happened-today'
    | '/teaching/workshops/reading-the-scene'
    | '/teaching/workshops/scenes-that-suck'
    | '/teaching/workshops/sneaking-up-on-yourself'
    | '/teaching/workshops/starting-over-and-over'
    | '/teaching/workshops/the-idiot'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/improvising'
    | '/me'
    | '/teaching'
    | '/teaching/workshops/big-me-mc-skills'
    | '/teaching/workshops/en-pointe'
    | '/teaching/workshops/nothing-happened-today'
    | '/teaching/workshops/reading-the-scene'
    | '/teaching/workshops/scenes-that-suck'
    | '/teaching/workshops/sneaking-up-on-yourself'
    | '/teaching/workshops/starting-over-and-over'
    | '/teaching/workshops/the-idiot'
  id:
    | '__root__'
    | '/'
    | '/improvising'
    | '/me'
    | '/teaching'
    | '/teaching/'
    | '/teaching/workshops/big-me-mc-skills'
    | '/teaching/workshops/en-pointe'
    | '/teaching/workshops/nothing-happened-today'
    | '/teaching/workshops/reading-the-scene'
    | '/teaching/workshops/scenes-that-suck'
    | '/teaching/workshops/sneaking-up-on-yourself'
    | '/teaching/workshops/starting-over-and-over'
    | '/teaching/workshops/the-idiot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImprovisingRouteRoute: typeof ImprovisingRouteRoute
  MeRouteRoute: typeof MeRouteRoute
  TeachingRouteRoute: typeof TeachingRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teaching': {
      id: '/teaching'
      path: '/teaching'
      fullPath: '/teaching'
      preLoaderRoute: typeof TeachingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/improvising': {
      id: '/improvising'
      path: '/improvising'
      fullPath: '/improvising'
      preLoaderRoute: typeof ImprovisingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teaching/': {
      id: '/teaching/'
      path: '/'
      fullPath: '/teaching/'
      preLoaderRoute: typeof TeachingIndexRouteImport
      parentRoute: typeof TeachingRouteRoute
    }
    '/teaching/workshops/the-idiot': {
      id: '/teaching/workshops/the-idiot'
      path: '/workshops/the-idiot'
      fullPath: '/teaching/workshops/the-idiot'
      preLoaderRoute: typeof TeachingWorkshopsTheIdiotRouteImport
      parentRoute: typeof TeachingRouteRoute
    }
    '/teaching/workshops/starting-over-and-over': {
      id: '/teaching/workshops/starting-over-and-over'
      path: '/workshops/starting-over-and-over'
      fullPath: '/teaching/workshops/starting-over-and-over'
      preLoaderRoute: typeof TeachingWorkshopsStartingOverAndOverRouteImport
      parentRoute: typeof TeachingRouteRoute
    }
    '/teaching/workshops/sneaking-up-on-yourself': {
      id: '/teaching/workshops/sneaking-up-on-yourself'
      path: '/workshops/sneaking-up-on-yourself'
      fullPath: '/teaching/workshops/sneaking-up-on-yourself'
      preLoaderRoute: typeof TeachingWorkshopsSneakingUpOnYourselfRouteImport
      parentRoute: typeof TeachingRouteRoute
    }
    '/teaching/workshops/scenes-that-suck': {
      id: '/teaching/workshops/scenes-that-suck'
      path: '/workshops/scenes-that-suck'
      fullPath: '/teaching/workshops/scenes-that-suck'
      preLoaderRoute: typeof TeachingWorkshopsScenesThatSuckRouteImport
      parentRoute: typeof TeachingRouteRoute
    }
    '/teaching/workshops/reading-the-scene': {
      id: '/teaching/workshops/reading-the-scene'
      path: '/workshops/reading-the-scene'
      fullPath: '/teaching/workshops/reading-the-scene'
      preLoaderRoute: typeof TeachingWorkshopsReadingTheSceneRouteImport
      parentRoute: typeof TeachingRouteRoute
    }
    '/teaching/workshops/nothing-happened-today': {
      id: '/teaching/workshops/nothing-happened-today'
      path: '/workshops/nothing-happened-today'
      fullPath: '/teaching/workshops/nothing-happened-today'
      preLoaderRoute: typeof TeachingWorkshopsNothingHappenedTodayRouteImport
      parentRoute: typeof TeachingRouteRoute
    }
    '/teaching/workshops/en-pointe': {
      id: '/teaching/workshops/en-pointe'
      path: '/workshops/en-pointe'
      fullPath: '/teaching/workshops/en-pointe'
      preLoaderRoute: typeof TeachingWorkshopsEnPointeRouteImport
      parentRoute: typeof TeachingRouteRoute
    }
    '/teaching/workshops/big-me-mc-skills': {
      id: '/teaching/workshops/big-me-mc-skills'
      path: '/workshops/big-me-mc-skills'
      fullPath: '/teaching/workshops/big-me-mc-skills'
      preLoaderRoute: typeof TeachingWorkshopsBigMeMcSkillsRouteImport
      parentRoute: typeof TeachingRouteRoute
    }
  }
}

interface TeachingRouteRouteChildren {
  TeachingIndexRoute: typeof TeachingIndexRoute
  TeachingWorkshopsBigMeMcSkillsRoute: typeof TeachingWorkshopsBigMeMcSkillsRoute
  TeachingWorkshopsEnPointeRoute: typeof TeachingWorkshopsEnPointeRoute
  TeachingWorkshopsNothingHappenedTodayRoute: typeof TeachingWorkshopsNothingHappenedTodayRoute
  TeachingWorkshopsReadingTheSceneRoute: typeof TeachingWorkshopsReadingTheSceneRoute
  TeachingWorkshopsScenesThatSuckRoute: typeof TeachingWorkshopsScenesThatSuckRoute
  TeachingWorkshopsSneakingUpOnYourselfRoute: typeof TeachingWorkshopsSneakingUpOnYourselfRoute
  TeachingWorkshopsStartingOverAndOverRoute: typeof TeachingWorkshopsStartingOverAndOverRoute
  TeachingWorkshopsTheIdiotRoute: typeof TeachingWorkshopsTheIdiotRoute
}

const TeachingRouteRouteChildren: TeachingRouteRouteChildren = {
  TeachingIndexRoute: TeachingIndexRoute,
  TeachingWorkshopsBigMeMcSkillsRoute: TeachingWorkshopsBigMeMcSkillsRoute,
  TeachingWorkshopsEnPointeRoute: TeachingWorkshopsEnPointeRoute,
  TeachingWorkshopsNothingHappenedTodayRoute:
    TeachingWorkshopsNothingHappenedTodayRoute,
  TeachingWorkshopsReadingTheSceneRoute: TeachingWorkshopsReadingTheSceneRoute,
  TeachingWorkshopsScenesThatSuckRoute: TeachingWorkshopsScenesThatSuckRoute,
  TeachingWorkshopsSneakingUpOnYourselfRoute:
    TeachingWorkshopsSneakingUpOnYourselfRoute,
  TeachingWorkshopsStartingOverAndOverRoute:
    TeachingWorkshopsStartingOverAndOverRoute,
  TeachingWorkshopsTheIdiotRoute: TeachingWorkshopsTheIdiotRoute,
}

const TeachingRouteRouteWithChildren = TeachingRouteRoute._addFileChildren(
  TeachingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImprovisingRouteRoute: ImprovisingRouteRoute,
  MeRouteRoute: MeRouteRoute,
  TeachingRouteRoute: TeachingRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
